# Author: @mvxt
##########################
# Orb Inclusions
##########################
orbs:
  aws-s3: circleci/aws-s3@1.0.8
  sumologic: circleci/sumologic@1.0.4
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-cli: circleci/aws-cli@0.1.19

##########################
# Common Definitions
##########################
# Simple YAML anchors
aliases:
  - &project_dir "~/project"

# Executors
executors:
  node-exec:
    docker:
      - image: cimg/python:3.6-node-browsers
    working_directory: *project_dir
    resource_class: medium

# Commands
commands:
  say-hello:
    description: "Show off parameterization and concurrent jobs"
    parameters:
      subject:
        type: string
        default: "World"
    steps:
      - run: echo "Hello << parameters.subject >>!"

##########################
# Workflow Definitions
##########################
workflows:
  version: 2
  build-deploy:
    jobs:
      - sumologic/workflow-collector:
          filters:
            branches:
              only: master
      - test
      - test-parallel:
          requires:
            - test
      - parameterized-command:
          requires:
            - test
      - approve:
          type: approval
          requires:
            - test-parallel 
            - parameterized-command 
          filters:
            branches:
              only: master
      - build-and-push-dockerhub:
          context: demo-prod
          requires:
            - approve
          filters:
            branches:
              only: master
      - aws-ecr/build-and-push-image:
          context: demo-prod
          requires:
            - approve
          repo: "$AWS_ECR_REPO_NAME"
          tag: "latest,${CIRCLE_SHA1}"
      - deploy:
          context: demo-prod
          requires:
            - build-and-push-dockerhub
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: master

  nightly:
    jobs:
      - test
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only: master

##########################
# Job Definitions
##########################
version: 2.1
jobs:
  test:
    executor: node-exec
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.1-dependencies-{{ checksum "package.json" }}
            - v1.1-dependencies-
      - run:
          name: Install deps
          command: yarn
      - save_cache:
          key: v1.1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run TestCafe Tests 
          command: |
            yarn test-ci 
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: . 
      - store_artifacts:
          path: ./results.html
      - persist_to_workspace:
          root: .
          paths:
            - Dockerfile
            - etc
            - css
            - img
            - index.html
            - js
            - mail
            - scss

  test-parallel:
    executor: node-exec
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.1-dependencies-{{ checksum "package.json" }}
            - v1.1-dependencies-
      - run:
          name: Install deps
          command: yarn
      - save_cache:
          key: v1.1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Glob, Split, and Run TestCafe Tests 
          command: |
            TESTFILES=$(circleci tests glob test/* | circleci tests split --total=4)
            echo "Testing $TESTFILES on this container"
            yarn test-ci -- ${TESTFILES}
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: . 
      - store_artifacts:
          path: ./results.html

  parameterized-command:
    executor: node-exec
    resource_class: small
    steps:
      - say-hello:
          subject: "World"
      - say-hello:
          subject: "Buddy"

  build-and-push-dockerhub:
    executor: node-exec
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build the Docker image, tag it
          command: docker build -t ${DOCKER_TAG} -t ${DOCKER_TAG}:${CIRCLE_SHA1} .
      - run:
          name: Login to DockerHub and push
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push ${DOCKER_TAG}
            docker push ${DOCKER_TAG}:${CIRCLE_SHA1}

  deploy:
    docker:
      - image: cimg/python:3.6
    working_directory: *project_dir
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: .
          to: "$AWS_S3_BUCKET_NAME" 

