# Author: @mvxt
##########################
# Orb Inclusions
##########################
orbs:
  aws-s3: circleci/aws-s3@1.0.8

##########################
# Common Definitions
##########################
# Simple YAML anchors
aliases:
  - &project_dir "~/circleci-se-challenge"
  - &bucket_name "s3://circleci-se-challenge"
  - &container_config
    docker:
      - image: circleci/node:10.15.1-browsers
    working_directory: *project_dir
    resource_class: medium

  # Anchoring common steps between two jobs
  - &common_steps
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install deps
          command: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Split TestCafe tests between containers and run them 
          command: |
            TESTFILES=$(circleci tests glob test/* | circleci tests split --total=${NUM_CONTAINERS})
            echo "Testing $TESTFILES on this container"
            yarn runTests -- ${TESTFILES}
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: . 
      - persist_to_workspace:
          root: .
          paths:
            - css
            - img
            - index.html
            - js
            - mail
            - scss
            - vendor

##########################
# Workflow Definitions
##########################
workflows:
  version: 2.1
  build-deploy:
    jobs:
      - test
      - test_parallel:
          requires:
            - test
      - some_other_job:
          context: orpheus-prod
          requires:
            - test
      - some_other_job:
          context: orpheus-stage
          requires:
            - test
      - build_and_push:
          context: orpheus-prod
          requires:
            - test_parallel
            - some_other_job
          filters:
            branches:
              only: master
      - approve:
          type: approval
          requires:
            - build_and_push
          filters:
            branches:
              only: master
      - deploy:
          context: orpheus-prod
          requires:
            - approve
          filters:
            branches:
              only: master

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master

    jobs:
      - test_parallel

##########################
# Job Definitions
##########################
version: 2.1
jobs:
  test:
    <<: *container_config # Uses aliases to refer to anchors. See common definitions
    <<: *common_steps # See common_steps above
    environment:
      NUM_CONTAINERS: 1

  test_parallel:
    <<: *container_config # See common definitions
    <<: *common_steps # See common_steps above
    parallelism: 4
    environment:
      NUM_CONTAINERS: 4

  some_other_job:
    docker:
      - image: circleci/node:10.15.1-browsers
      - image: postgres:9.4.1
    working_directory: *project_dir
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Verify that we transferred index.html over
          command: test -f index.html
      - run:
          name: Sleep for 15 seconds to show PSQL database running
          command: sleep 15
      - run:
          name: Show files in directory
          command: ls -al
      - run:
          name: Echo env var from differing contexts
          command: echo "$TEST_VAR"

  build_and_push:
    <<: *container_config # See common definitions
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Tar required folders
          command: tar -czf dirs.tar.gz css img js mail scss vendor
      - run:
          name: Build the Docker image, tag it
          command: docker build -t mikeyvxt/slc-devops-2019 -t mikeyvxt/slc-devops-2019:${CIRCLE_SHA1} .
      - run:
          name: Login to docker hub and push
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push mikeyvxt/slc-devops-2019
            docker push mikeyvxt/slc-devops-2019:${CIRCLE_SHA1}

  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: *project_dir
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: .
          to: *bucket_name

